version: '3.8'

services:
  mynginx:
    build: .
    container_name: mynginx
    ports:
      - "${NGINX_HTTP_EXTERNAL_PORT}:80"
      - "${NGINX_HTTPS_EXTERNAL_PORT}:443"
    volumes:
      - ./www/data:/var/www/html
